### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by qinezh** [docascode/markdown#33]
# Roadmap for MarkdigEngine

### In MarkdigEngine
- [x] Support code snippet
- [x] Support file inclusion
- [x] Support line number info for reports
- [x] Support Note/Warning/Important
- [x] Support cross reference(xref)
- [x] Support YML header
- [x] Support rewrite framework
- [x] Support markdown validation
- ~~Support plug-in framework to customize MarkdigEngine~~
- [x] Support tabbed contents
- [x] Support tab combining
- [x] Support to rewrite title id for locale issue
- [x] Support moniker range syntax
- [x] Support interactive code
